remote_theme: pages-themes/cayman@v0.2.0
title: ECE4160 Fast Robots
.home-button {
  position: fixed;
  top: 15px;
  left: 15px;
  background-color: #333;
  color: white;
  padding: 8px 12px;
  border-radius: 6px;
  text-decoration: none;
  font-weight: bold;
  font-size: 14px;
  z-index: 1000;
}

.home-button:hover {
  background-color: #555;
}

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


